-- ---------------------------------------------------------------------------
-- 010 mentor scoring: fortnightly report cards with data-reliability signals
--
-- Closed scores are snapshots. Every number on a report card is stored with
-- its numerator, denominator and the immutable configuration version that
-- produced it, so history never moves when configuration is edited later.
-- ---------------------------------------------------------------------------

CREATE TYPE visit_location_status AS ENUM ('verified', 'exception', 'unverified', 'failed');
CREATE TYPE flag_kind             AS ENUM ('inflation', 'contradiction');
CREATE TYPE flag_severity         AS ENUM ('low', 'medium', 'high');
CREATE TYPE flag_status           AS ENUM ('new', 'in_review', 'confirmed', 'dismissed', 'escalated');
CREATE TYPE scoring_period_status AS ENUM ('open', 'closed');
CREATE TYPE score_status          AS ENUM ('final', 'provisional', 'insufficient_data');
CREATE TYPE exclusion_kind        AS ENUM ('training', 'outage', 'school_closed', 'other');

-- Who is a mentor, and the context scoring needs about them. A user without a
-- row here is simply not scored.
CREATE TABLE mentor_profiles (
  user_id     UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  mentor_role TEXT NOT NULL DEFAULT 'mentor',
  district    TEXT,
  block       TEXT,
  -- Assignment window; open-ended on either side when null.
  active_from DATE,
  active_to   DATE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT mentor_active_ordered CHECK (active_from IS NULL OR active_to IS NULL OR active_from <= active_to)
);
CREATE INDEX mentor_profiles_org_idx ON mentor_profiles (org_id, district, block);

-- Immutable, published configuration versions. A version applies from the
-- first scoring period starting on or after effective_from.
CREATE TABLE mentor_score_configs (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id         UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  version        INTEGER NOT NULL CHECK (version > 0),
  config         JSONB NOT NULL,
  effective_from DATE NOT NULL,
  note           TEXT,
  created_by     UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, version)
);

-- Published versions can never be edited or removed on their own. Deleting the
-- whole organization still has to work (its rows cascade), so a DELETE is only
-- refused while the owning organization exists.
CREATE FUNCTION forbid_config_mutation() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND NOT EXISTS (SELECT 1 FROM organizations WHERE id = OLD.org_id) THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION '% on % is not allowed: published configuration versions are immutable', TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER mentor_score_configs_immutable
  BEFORE UPDATE OR DELETE ON mentor_score_configs
  FOR EACH ROW EXECUTE FUNCTION forbid_config_mutation();

CREATE TABLE scoring_periods (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  start_date        DATE NOT NULL,
  end_date          DATE NOT NULL,
  status            scoring_period_status NOT NULL DEFAULT 'open',
  -- Bound when the period closes; null while open.
  config_version_id UUID REFERENCES mentor_score_configs(id),
  closed_at         TIMESTAMPTZ,
  -- Shadow mode: scores exist but mentors cannot see them until published.
  published_at      TIMESTAMPTZ,
  created_by        UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, start_date),
  CONSTRAINT scoring_period_ordered CHECK (start_date <= end_date),
  CONSTRAINT scoring_period_closed_complete CHECK (
    (status = 'open' AND closed_at IS NULL AND config_version_id IS NULL)
    OR (status = 'closed' AND closed_at IS NOT NULL AND config_version_id IS NOT NULL)
  )
);

-- Mentoring visits. The id is generated by the client, which is what makes
-- submission idempotent across retries and offline re-sync.
CREATE TABLE mentoring_visits (
  id                  UUID PRIMARY KEY,
  org_id              UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  mentor_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  school_id           TEXT NOT NULL CHECK (length(btrim(school_id)) > 0),
  visit_type          TEXT NOT NULL DEFAULT 'standard',
  started_at          TIMESTAMPTZ NOT NULL,
  ended_at            TIMESTAMPTZ NOT NULL,
  -- Offline visits are submitted later; validation uses started/ended.
  submitted_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed           BOOLEAN NOT NULL DEFAULT TRUE,
  assignment_valid    BOOLEAN NOT NULL DEFAULT TRUE,
  location_status     visit_location_status NOT NULL DEFAULT 'verified',
  is_test             BOOLEAN NOT NULL DEFAULT FALSE,
  cancelled_at        TIMESTAMPTZ,
  deleted_at          TIMESTAMPTZ,
  spot_applicable     INTEGER NOT NULL DEFAULT 0 CHECK (spot_applicable >= 0),
  spot_completed      INTEGER NOT NULL DEFAULT 0 CHECK (spot_completed >= 0),
  -- Observation-level checks the rule engine could evaluate on this visit.
  inflation_checks    INTEGER NOT NULL DEFAULT 0 CHECK (inflation_checks >= 0),
  consistency_checks  INTEGER NOT NULL DEFAULT 0 CHECK (consistency_checks >= 0),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX mentoring_visits_mentor_started_idx ON mentoring_visits (mentor_id, started_at);
CREATE INDEX mentoring_visits_org_started_idx ON mentoring_visits (org_id, started_at);

-- Days removed from the expected-visit denominator: approved training,
-- declared system outages, authorised school closures. user_id null applies
-- to every mentor (an org-wide outage). Approved leave comes from
-- leave_requests and is not duplicated here.
CREATE TABLE scoring_exclusions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id    UUID REFERENCES users(id) ON DELETE CASCADE,
  kind       exclusion_kind NOT NULL,
  start_date DATE NOT NULL,
  end_date   DATE NOT NULL,
  reason     TEXT NOT NULL CHECK (length(btrim(reason)) > 0),
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT exclusion_range_ordered CHECK (start_date <= end_date)
);
CREATE INDEX scoring_exclusions_lookup_idx ON scoring_exclusions (org_id, start_date, end_date);

CREATE TABLE quality_flags (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  mentor_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  visit_id            UUID NOT NULL REFERENCES mentoring_visits(id) ON DELETE CASCADE,
  rule_code           TEXT NOT NULL,
  kind                flag_kind NOT NULL,
  severity            flag_severity NOT NULL DEFAULT 'medium',
  status              flag_status NOT NULL DEFAULT 'new',
  -- Shown to the mentor; internal rule ids never are.
  explanation         TEXT NOT NULL,
  evidence_payload    JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  confirmed_at        TIMESTAMPTZ,
  resolved_at         TIMESTAMPTZ,
  -- Set when a flag confirmed after its period closed has been applied to a
  -- score (the next period under carryover, or the original under an explicit
  -- recalculation). Stops one confirmation from counting twice.
  carried_into_period_id UUID REFERENCES scoring_periods(id),
  UNIQUE (visit_id, rule_code),
  CONSTRAINT flag_confirmed_has_time CHECK ((status = 'confirmed') = (confirmed_at IS NOT NULL))
);
CREATE INDEX quality_flags_mentor_idx ON quality_flags (mentor_id, status);
CREATE INDEX quality_flags_queue_idx ON quality_flags (org_id, status, created_at);

CREATE TABLE audit_reviews (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  flag_id     UUID NOT NULL REFERENCES quality_flags(id) ON DELETE CASCADE,
  reviewer_id UUID REFERENCES users(id) ON DELETE SET NULL,
  decision    TEXT NOT NULL CHECK (decision IN ('start_review', 'confirm', 'dismiss', 'escalate', 'note')),
  from_status flag_status NOT NULL,
  to_status   flag_status NOT NULL,
  reason_code TEXT,
  note        TEXT,
  decided_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_reviews_flag_idx ON audit_reviews (flag_id, decided_at);

-- One row per calculation. Recalculation inserts a new version and moves
-- is_current; nothing is overwritten.
CREATE TABLE mentor_scores (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  mentor_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period_id         UUID NOT NULL REFERENCES scoring_periods(id) ON DELETE CASCADE,
  version           INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  is_current        BOOLEAN NOT NULL DEFAULT TRUE,
  overall           NUMERIC(5,2) CHECK (overall BETWEEN 0 AND 100),
  compliance        NUMERIC(5,2) CHECK (compliance BETWEEN 0 AND 100),
  reliability       NUMERIC(5,2) CHECK (reliability BETWEEN 0 AND 100),
  status            score_status NOT NULL,
  status_reasons    TEXT[] NOT NULL DEFAULT '{}',
  under_review      BOOLEAN NOT NULL DEFAULT FALSE,
  evidence_counts   JSONB NOT NULL,
  config_version_id UUID NOT NULL REFERENCES mentor_score_configs(id),
  calculated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  recalculated_at   TIMESTAMPTZ,
  UNIQUE (mentor_id, period_id, version)
);
CREATE UNIQUE INDEX mentor_scores_current_idx ON mentor_scores (mentor_id, period_id) WHERE is_current;
CREATE INDEX mentor_scores_period_idx ON mentor_scores (period_id) WHERE is_current;

CREATE TABLE mentor_score_metrics (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mentor_score_id    UUID NOT NULL REFERENCES mentor_scores(id) ON DELETE CASCADE,
  metric_code        TEXT NOT NULL,
  numerator          NUMERIC(10,2) NOT NULL,
  denominator        NUMERIC(10,2) NOT NULL,
  raw_value          NUMERIC(5,2),
  weight             NUMERIC(6,4) NOT NULL,
  effective_weight   NUMERIC(6,4) NOT NULL,
  weighted_value     NUMERIC(5,2) NOT NULL,
  rule_version       INTEGER NOT NULL,
  applicability_status TEXT NOT NULL CHECK (applicability_status IN ('applicable', 'not_applicable')),
  UNIQUE (mentor_score_id, metric_code)
);

CREATE TABLE score_events (
  id         BIGSERIAL PRIMARY KEY,
  org_id     UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  mentor_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period_id  UUID NOT NULL REFERENCES scoring_periods(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('calculated', 'recalculated', 'published')),
  before_value JSONB,
  after_value  JSONB,
  actor_id   UUID REFERENCES users(id) ON DELETE SET NULL,
  reason     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX score_events_mentor_idx ON score_events (mentor_id, period_id, created_at);

CREATE TABLE benchmark_snapshots (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  period_id         UUID NOT NULL REFERENCES scoring_periods(id) ON DELETE CASCADE,
  geography         TEXT NOT NULL,           -- district name, or '*' for org-wide
  mentor_role       TEXT NOT NULL,
  cohort_definition JSONB NOT NULL,          -- member ids, data window
  statistic         TEXT NOT NULL DEFAULT 'median',
  value             NUMERIC(5,2),            -- null when suppressed
  cohort_size       INTEGER NOT NULL,
  suppressed        BOOLEAN NOT NULL,
  cap_method        TEXT NOT NULL DEFAULT 'one_value_per_mentor_median',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (period_id, geography, mentor_role)
);
